spring:
  profiles:
    active: local
    include: my
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
com:
  example:
    upload:
      path: upload
